resolver: lts-19.25

packages:
- .

extra-deps:
- unicode-data-0.3.0
- bytestring-0.11.3.1
- directory-1.3.8.0
- text-1.2.5.0
- binary-0.8.9.1
- filepath-1.4.100.0
- unix-2.8.0.0
- github: composewell/streamly
  commit: "master"
- github: composewell/streamly
  commit: "master"
  subdirs:
    - core

# Look at https://stackoverflow.com/questions/70045586/could-not-find-module-system-console-mintty-win32-when-compiling-test-framework
flags:
  mintty:
    Win32-2-13-1: false
